### ISSUE TITLE
ziti.LoadContext(path) not idempotent - crashes when called twice

### ISSUE THREAD

**Issue by dovholuknf** [openziti/sdk-golang#345] opened 2023-01-11 01:48 UTC
**Observed:**
Panic when calling `ctx, err = ziti.LoadContext(idFile)` twice

**Expected:**
I didn't know what I expected, but I think it probably makes sense for this to be idempotent -- or at very least it should not panic 

**Stack**
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x70b2a5]

goroutine 1 [running]:
github.com/openziti/sdk-golang/ziti/edge/api.(*lazyClient).Shutdown(0xc000458680)
        <autogenerated>:1 +0x25
github.com/openziti/sdk-golang/ziti.(*contextImpl).Close(0xc00023e3c0)
        C:/Users/clint/go/pkg/mod/github.com/openziti/sdk-golang@v0.18.24/ziti/ziti.go:1077 +0x32a
github.com/openziti/sdk-golang/ziti.LoadContext({0xc00003d9c0, 0x23})
        C:/Users/clint/go/pkg/mod/github.com/openziti/sdk-golang@v0.18.24/ziti/contexts.go:59 +0x3fd
github.com/edgexfoundry/edgex-ui-go/internal.initClientsMapping(0xc000228c00)
        V:/work/git/github/external/edgex/edgex-ui-go/internal/application.go:65 +0x285
```

**Comment by plorenz** [comment] 2023-09-26 17:52
I was taking a look at fixing this while I was in the sdk code, but I suspect it's already been fixed. The lazyClient type is no more. 
I tried it in a sample program, and was unable to reproduce the panic. I tried calling LoadContext twice and NewContext twice, and both were ok. Closing, but if this still happens, please re-open.

**Closed by plorenz** 2023-09-26 17:52 UTC
Labels: bug
